### PR TITLE
Replace local cert with bucket object

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch adjusts the private-tcp-active-active job to use an existing proxy certificate found in the external bootstrap bucket.

## How Has This Been Tested

To be tested here!

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by aaron-lane** [comment]
@anniehedgpeth looks like we're clear for a review!

**Review by anniehedgpeth — APPROVED** [review]
🎉

**Pull request merged**
