### PR TITLE
Ah use base image

### PR DESCRIPTION
**Pull request by anniehedgpeth**
### Description
As a module maintainer, I would like to use a base image in the Public Active/Active test so that I can verify the functionality of the image and also begin moving prerequisite dependencies out of the TFE install script. The prereqs will remain in there with conditionals until a decision is made about whether or not to remove them.

## How Has This Been Tested

These changes were tested locally with our current base image AMI id which is now stored as a variable in the Terraform workspace running these tests.

## This PR makes me feel

images

### CODE REVIEW

**Comment by aaron-lane** [comment]
@anniehedgpeth can you please rebase the branch? There are commits in the history that are already merged. 🕵🏼

**Comment by anniehedgpeth** [comment]
> @anniehedgpeth can you please rebase the branch? There are commits in the history that are already merged. 🕵🏼

Whew, that was a gnarly rebase, but I'm finished now. Thanks!

**Comment by anniehedgpeth** [comment]
Closing since image project is scrapped.

**Pull request closed without merging**
