### PR TITLE
aaron-lane-delint-personas-retailer

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

Linting is included as part of the new CI system. As the module redesign was done before we decided on the linting rules to enforce, there are a number of existing issues that need to be addressed. This branch focuses on the retailer persona example.

This branch also disables forced pass of tflint so it is expected to fail until the preceding pull requests have been merged.

[Asana task](https://app.asana.com/0/1181500399442529/1200170182808309/f)

## How Has This Been Tested

I'm running tflint locally as I work, and our GitHub Actions configuration will confirm that the issues are fixed.

## This PR makes me feel

A wobbly walking llama

### CODE REVIEW

**Review by anniehedgpeth — APPROVED** [review]

**Comment by anniehedgpeth** [comment]
Looks like l approved before noticing [this](https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/109/checks?check_run_id=2325260841) failure.

**Comment by rogeruiz** [comment]
Re-running the jobs as the other PRs have landed in the default branch.

**Comment by rogeruiz** [comment]
@aaron-lane looks like `examples/*` is failing because they only contain a `README.md`

**Comment by rogeruiz** [comment]
This is fixed in #110

**Review by rogeruiz — APPROVED** [review]
LGTM 🌈

**Pull request merged**
