### PR TITLE
Convert personas-retailer to private-active-active

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch converts the Retailer Persona example to the Private Active/Active test case.

Relates #153

## How Has This Been Tested

It will be tested here!

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by aaron-lane** [comment]
/test
🤞🏼

**Comment by aaron-lane** [comment]
The failure of the Public Active/Active test was expected and can be ignored.

**Review by anniehedgpeth — DISMISSED** [review]
Looks good!

**Review by anniehedgpeth — APPROVED** [review]

**Pull request merged**
