### PR TITLE
Use undefined variable

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch intentionally breaks a variable reference to confirm that the validate step works correctly.

Relates #120

## How Has This Been Tested

This _is_ the test :boom:

## This PR makes me feel

A person saying "It feels good to be validated"

### CODE REVIEW

**Comment by rogeruiz** [comment]
So is validation always going to fail because `region` isn't set and expected to be passed in by environment variable?

**Comment by aaron-lane** [comment]
@rogeruiz this is addressed by #122.

**Comment by aaron-lane** [comment]
Closing as the test was a success!

**Pull request closed without merging**
