### PR TITLE
[DO NOT MERGE] Break the terraform init to see it fail

### PR DESCRIPTION
**Pull request by rogeruiz**
Elmo with hands up in front of a wall of fire

### CODE REVIEW

**Comment by rogeruiz** [comment]
/test

cc: @aaron-lane and @anniehedgpeth Let's see how errors are reported on test commands

**Comment by hc-team-tfe** [comment]
#### Terraform Test Report 📰

#### Terraform Initialization ⚙️\`success\`

<details>
<summary>
<b>Terraform Initialization Output</b> ⚙️
</summary>

\`\`\`${process.env.INIT_STDOUT}\`\`\`
\`\`\`${process.env.INIT_STDERR}\`\`\`

</details>

[Action Run Page][1]

[1]: https://github.com/hashicorp/terraform-aws-terraform-enterprise/actions/runs/746033749

**Comment by rogeruiz** [comment]
/test

Another attempt at generating a test report for `tests/public-install`.

**Comment by rogeruiz** [comment]
/test

A final test with all the updates from #111, #114, #115

**Comment by rogeruiz** [comment]
Ugh, trial and error. #116 should fix all the issues shown in this test

**Comment by rogeruiz** [comment]
/test

The real final test on this

**Comment by rogeruiz** [comment]
Uh oh @aaron-lane i think I focused too much on the feedback formatting and not the actual feedback. All of these tests should have come back as failures and not successes. 🤦

**Comment by aaron-lane** [comment]
@rogerruiz The output shows the initialization succeeded, and also shows several modules being installed, which doesn't align with the change you made to the branch. I wonder if the handler is running in the context of the main branch. 😬

**Comment by rogeruiz** [comment]
/test

Do tests run on closed PRs? Let's find out.

**Comment by rogeruiz** [comment]
☝🏽 @aaron-lane This is a weird thing. @chrisfishwood shouldn't have triggered the `/test` command.

**Pull request closed without merging**
