### PR TITLE
Add in handler test feedback & cleanup names

### PR DESCRIPTION
**Pull request by rogeruiz**
## Background

When the `/slash` commands were introduced in #100, there is no feedback that a command was done or where that command ran. This patch adds an emoji reaction (🎉) and adds a GitHub Action to comment on the PR a link to the output of the command.

## How Has This Been Tested

It will need to be tested after it is merged as it's specifically tied to the workflow of GitHub Actions and comments on PRs.

### Test Configuration

* Terraform Version: n/a
* Any additional relevant variables: n/a

## This PR makes me feel

Casimiro Morales checks for feedback on his old flip phone

### CODE REVIEW

**Review by aaron-lane — COMMENTED** [review]
Can we have the comment sent unconditionally? I think we will want to highlight both successes and failures. We could also use the [job status check functions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) if we want to react with differing emojis.

**Comment by rogeruiz** [comment]
/help

Testing out the `/help` command that was merged from #112

**Comment by rogeruiz** [comment]
A small issue I see with how the `/test` command is set up now is that it runs all the jobs in the `handler-test.yml` file. This is fine when there is one, but with multiple tests, I think it might be better to pass in options such as `/test public-install` to isolate tests. The reasoning behind this is that the @hc-team-tfe bot will update the pull request comment that initiated the command and if we're running multiple modules through the `/test` command, we could hit a race condition that edits/comments/deletes comments that update the PR comment that initiated the run.

**Review by aaron-lane — APPROVED** [review]
@rogeruiz agreed about the need to add test targets! We can iterate once we finish the workflow for the initial test case.

LGTM 🌬️

**Review by anniehedgpeth — APPROVED** [review]

**Pull request merged**
