### PR TITLE
Update to be v0.12.x compatible

### PR DESCRIPTION
**Pull request by ed-brex**
These were the changes I made to get the module working for myself. I haven't done any testing beyond getting it working

--- 

* Use `0.12upgrade` to auto-update code
* Make a number of manual changes to fix initial incompatibilities
    * Addresses https://github.com/hashicorp/terraform-aws-terraform-enterprise/issues/35
* Perform general cleanup (i.e. remove unneeded interpolation)
* Have some inline policies be defined by iam_document data
* Update .gitignore to include `.terraform`

### CODE REVIEW

**Comment by evanphx** [comment]
Hi thank you for the PR! We're not going to merge this sadly because we need the modules to be compatible with 0.11 as well for now.

**Comment by ed-brex** [comment]
Do you mean the modules within the repo? Is it possible to have a different release/branch for 0.12? If not, is there a timeline when 0.12 will be upstreamed? We're fine hosting internally, but an "official/stamped" version would help our general confidence (maybe prevent additional forks?).

**Comment by evanphx** [comment]
Yes, that's correct the modules in this repo should work with 0.11 and 0.12. I'd rather not have two versions we have to keep up to date. If you'd like to help out with this, getting the modules working without doing the syntax conversions to 0.12 is the way to go. That way it can work both places.

**Comment by ed-brex** [comment]
Yeah, I'd be down to take a crack at it. Might have some time later this week.

**Comment by bnferguson** [comment]
@ed-brex Closing this one out in favor of https://github.com/hashicorp/terraform-aws-terraform-enterprise/pull/45, thanks so much for getting it started! 🙌

**Pull request closed without merging**
