### PR TITLE
Move public-install to public-active-active

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch renames public-install to public-active-active and adjusts the Terraform configuration accordingly. It also explicitly sets the instance type for transparency and uses a slighly more generically named license file.

Relates #144

## How Has This Been Tested

It will be tested here once #144 is merged.

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by aaron-lane** [comment]
@anniehedgpeth tests have passed!

**Review by anniehedgpeth — APPROVED** [review]
Woohoo!!

**Pull request merged**
